[options]
addons_path=/mnt/extra-addons/self
# addons_path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons/addons,/mnt/extra-addons/enterprise-16,/mnt/extra-addons/git/mod_free_16,/mnt/extra-addons/mod_add/plataforma_addons,/mnt/extra-addons/mod_add/solse_addons,/mnt/extra-addons/mod_add/solse_erp_dependencias,/mnt/extra-addons/mod_add/solse_peru_contabilidad,/mnt/extra-addons/mod_add/solse_peru_cpe
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
server_mode = 
server_wide_modules = web
limit_time_real = 300
xmlrpc = True
xmlrpc_port = 8069
admin_passwd = 12345

